{
 "title": "Agent Security",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agentname",
    "label": "Agent",
    "query": "{\"find\": \"terms\", \"field\":\"agent.name\",\"size\": \"1000000\" }"
   },
   {
    "name": "rulelevel",
    "label": "Rules Level",
    "query": "{\"find\": \"terms\", \"field\":\"rule.level\",\"query\":\"agent.name:$agentname\",\"size\": \"1000000\" }"
   },
   {
    "name": "vulnerabilityseverity",
    "label": "Vulnerability Severity",
    "query": "{\"find\": \"terms\", \"field\":\"data.vulnerability.severity\",\"size\": \"1000000\" }"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "TOP MITRE ATT&CKS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.mitre.technique",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Rules Fires",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.firedtimes",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.id",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Events Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.description",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "ALERTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ALERTS",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "# Title\n\n  For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Authentication failure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.groups: ((authentication_failure) OR (win_authentication_failed) OR (authentication_failures))",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Auhentication succes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.groups:authentication_success",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert level evolution ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:[12 TO *] AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Alerts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.description",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.description",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.groups",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Security Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.firedtimes",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent.ip",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.description",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.groups",
       "id": "16",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.id",
       "id": "17",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "22",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert Information",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "agent.name: $agentname AND rule.level:$rulelevel AND !data.vulnerability.cve:*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "WAZUH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "WAZUH",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "# Title\n\n  For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wazuh Rules BrakeDown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.groups",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wazuh PC-DSS Controls",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.pci_dss",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agentname AND rule.level:$rulelevel",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "VULNERABILITIES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "VULNERABILITIES",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "options": {
    "content": "# Title\n\n  For markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n           "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Vulnerability Risks",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: Critical AND agent.name:$agentname AND rule.level:$rulelevel",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: High AND agent.name:$agentname AND rule.level:$rulelevel",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: Medium AND agent.name:$agentname AND rule.level:$rulelevel",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.severity: Low AND agent.name:$agentname AND rule.level:$rulelevel",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 5 CVE",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.cve",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.groups: vulnerabili* AND agent.name:$agentname AND rule.level:$rulelevel AND data.vulnerability.severity: $vulnerabilityseverity",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Vulnerabilites",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.cve",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cvss.cvss3.vector.integrity_impact",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cvss.cvss3.vector.access_complexity",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cvss.cvss3.vector.privileges_required",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.rationale",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.groups: vulnerabili* AND agent.name:$agentname AND rule.level:$rulelevel AND data.vulnerability.severity: $vulnerabilityseverity",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Vulerabilities by Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.groups: vulnerabili* AND agent.name:$agentname AND rule.level:$rulelevel",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Vulnerabilities Information",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "agent.name: $agentname AND data.vulnerability.severity: $vulnerabilityseverity",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}