{
 "title": "Alerts Security",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rulelevel",
    "label": "Rule Level",
    "query": "{\"find\": \"terms\", \"field\":\"rule.level\",\"query\":\"agent.name:*\",\"size\": \"1000000\" }"
   },
   {
    "name": "ruleid",
    "label": "ID Rule ",
    "query": "{\"find\": \"terms\", \"field\":\"rule.id\",\"query\":\"agent.name:*\",\"size\": \"1000000\" }"
   },
   {
    "name": "agentname",
    "label": "Agent Name",
    "query": "{\"find\": \"terms\", \"field\":\"agent.name\",\"query\":\"!agent.name:wazuh-*\",\"size\": \"1000000\" }"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Max Level Alert Security ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "!data.vulnerability.cve:* AND agent.name:$agentname AND rule.id:$ruleid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CRITICAL ALERTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:>10 AND !data.vulnerability.cve:* AND rule.level:$rulelevel AND rule.id:$ruleid AND agent.name:$agentname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HIGH ALERTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " rule.level: (>7 AND <11) AND !data.vulnerability.cve:* AND rule.level:$rulelevel AND rule.id:$ruleid AND agent.name:$agentname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MEDIUM ALERTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level: (>5 AND <8) AND !data.vulnerability.cve:* AND rule.level:$rulelevel AND rule.id:$ruleid AND agent.name:$agentname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "LOW ALERTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level: <6 AND !data.vulnerability.cve:* AND rule.level:$rulelevel AND rule.id:$ruleid AND agent.name:$agentname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alerts Evolution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "alias": "LOW",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "sum" }
     ],
     "query": "rule.level:<6 AND rule.level: $rulelevel AND rule.id: $ruleid",
     "timeField": "@timestamp"
    },
    {
     "alias": "MEDIUM",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "sum" }
     ],
     "query": "rule.level: (>5 AND <8) AND rule.level: $rulelevel AND rule.id: $ruleid",
     "timeField": "@timestamp"
    },
    {
     "alias": "HIGH",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "sum" }
     ],
     "query": "rule.level: (>7 AND <11) AND rule.level: $rulelevel AND rule.id: $ruleid",
     "timeField": "@timestamp"
    },
    {
     "alias": "CRITICAL",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "sum" }
     ],
     "query": "rule.level:>10 AND rule.level: $rulelevel AND rule.id: $ruleid",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "agent.ip",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.description",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent.id",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.id",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.firedtimes",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "!data.vulnerability.cve:* AND rule.level:$rulelevel AND rule.id:$ruleid AND agent.name:$agentname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alert Information",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "!data.vulnerability.cve:* AND rule.level:$rulelevel AND rule.id:$ruleid AND agent.name:$agentname",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}