{
 "title": "MAIN DASHBOARD",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serversname",
    "label": "Servers Names",
    "query": "{\"find\": \"terms\", \"field\":\"name\",\"query\":\"group:SERVER\",\"size\": \"1000000\" }"
   }
  ]
 },
 "panels": [
  {
   "title": "INFRAESTRUCTURE",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\"> \n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"> \n       <img src=\"https://apoloanalytics.com/wp-content/uploads/2022/06/ApoloAnalytics_Vertical_White.png\"   width=\"89%\"> \n     </td> \n</table>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SECURITY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "!data.vulnerability.cve: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FIREWALLS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "rule.groups: fortigate",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VULNERABILITIES",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "data.vulnerability.cve: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule.level", "id": "1", "type": "max" }
     ],
     "query": "rule.groups: suricata",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\"> \n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \">\n        <img src=\"https://apoloanalytics.com/wp-content/uploads/2022/06/Logo-LE-W.png\"   width=\"70%\" >\n     </td> \n</table>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "EXTERNAL ATTACKS",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.description",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.srcip",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "GeoLocation.country_name",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.level",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "GeoLocation.location", "id": "8", "settings": { "precision": "3" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SERVERS",
   "type": "marcusolsson-hexmap-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "status",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "ip",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "status",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "group:SERVER",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Light Eyes News and Alerts",
   "type": "news",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "status",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "ip",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "status",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "group:SERVER",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": " rule.level:>10 AND !data.vulnerability.cve: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CRITICAL ALERTS",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 3, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "agent.ip",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.description",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level: >7 AND !data.vulnerability.cve: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Security Alerts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.level",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:(>7 AND <11) AND !data.vulnerability.cve: *",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.level",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:<6 AND !data.vulnerability.cve: *",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.level",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level: (>5 AND <8) AND !data.vulnerability.cve: *",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "rule.level",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule.level:>10 AND !data.vulnerability.cve: *",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VULNERABILITIES",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.vulnerability.cve: *",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}