apiVersion: v1
kind: Service
metadata:
  name: rest-api
  namespace: apolo
  labels:
    app: rest-api
  annotations:
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: rest-api
  type: LoadBalancer