apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim-deployment
  labels:
    app: victim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: victim
  template:
    metadata:
      labels:
        app: victim
    spec:
      containers:
      - name: victim
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80