apiVersion: v1
kind: Service
metadata:
  name: victim
  namespace: infraestructure
  labels:
    app: victim
spec:
  type: LoadBalancer
  selector:
    app: victim
  ports:
    - name: http
      port: 80
      targetPort: 80