apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  source:
    path: apps/infrastructure
    repoURL: https://github.com/ArnolSwet/tfg_arnau-cirera_ub2022-2023.git
    targetRevision: testing
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infrastructure
  project: default