apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    path: apps/grafana/app
    repoURL: https://github.com/ArnolSwet/tfg_arnau-cirera_ub2022-2023.git
    targetRevision: testing
    helm:
      values: values-testing.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  project: default